### ISSUE TITLE
Add function error

### ISSUE THREAD

**Issue by apovn** [rakshitshah94/Angular2-SpringBoot-Example#1]
When I click add button, I get below error:
error:"Internal Server Error"
exception:"org.springframework.orm.jpa.JpaSystemException"
message:"The database returned no natively generated identity value; nested exception is org.hibernate.HibernateException: The database returned no natively generated identity value"
path:"/api/person"
status:500
timestamp:1505362623524

**Comment by rakshitshah94** [comment]
**Hello @apovn ,** 
It seems an issue with the version of the JDBC driver, or Make sure that while creating your table id field should be marked as auto-increment and then use
`@GeneratedValue(strategy = GenerationType.IDENTITY)`

That Exception can also occur if the @id annotated property mapped column dose not support auto generation of id. That is
`@GeneratedValue(strategy = GenerationType.AUTO)`
Use `@GeneratedValue(strategy = GenerationType.IDENTITY)`
Hope so this might solve the problem. In case if this not working, let me know your versions and configurations. I will try to resolve it.

**Thanks,
The Rax**
