### ISSUE TITLE
no QPerson class

### ISSUE THREAD

**Issue by qiucaixiu** [rakshitshah94/Angular2-SpringBoot-Example#2]
Hi,
While I imported this project, we found there is no class 'net.mzouabi.ng2.server.model.QPerson'.
We found 'net.mzouabi.ng2.server.model.Person', but in Person class, there is no public element: 'person' and 'id'. Waiting for your response.

Regards
Ethan

**Comment by rakshitshah94** [comment]
Hello Ethan,
Thanks for your question, really appreciated. I understand your problem. 
When you Import this project, You need to fulfill the requirements.

**If you have imported project in eclipse, Follow this steps to build project:**
1. Right click on project > Properties > **Java Build path**
2. Change your **JDK if 1.8 is not set.**
3. You need **Maven 3+** configured in your system (or You can download Maven 3+ from [here](https://maven.apache.org/download.cgi))
4. Once you setup with all this things,
Right click on project > Run as > Maven clean (you can directly do this using **mvn clean** command in cmd at specific project dir)
5. Again right click on project, Find **Maven >** in options, Click on **Update project**
check **Update snapshots forcefully** option and press ok.
6. Now you can refresh your project. Run clean and build project.
7. **Main Important step >** Right click on project > Run as  > **Maven Install**
 This step will install required dependency specified in [pom.xml](https://github.com/rakshitshah94/Angular2-SpringBoot-Example/blob/master/server/pom.xml) file

Now as per your question, **QPerson is missing**
Once you follow above steps it will be generated automatically in 
../Project_Dir/target/net/../server/model/QPerson.java

**You may have question that how this was generated ?**
If you observed libraries (Dependencies) in pom.xml ,
```
<dependency>
	<groupId>com.h2database</groupId>
	<artifactId>h2</artifactId>
	<scope>runtime</scope>
</dependency>
```
You need to know more about [H2 Database](https://en.wikipedia.org/wiki/H2_(DBMS)). 
H2 is a relational database management system written in Java. It can be embedded in Java applications or run in the client-server mode.
- Very fast, open source, JDBC API
- Embedded and server modes; in-memory databases (Simple meaning => data will not persist on the disk)
- lightweight Java database
- It can be embedded in Java applications or run in the client-server mode
Whatever things (Objects, String or anything) you want to store in **H2** you can.
In this example, whatever values you want to store (CRUD operations), it will be retain in H2 Database till you shutdown your tomcat.(or other servers). 

Hope so you get idea about this things. 
**Thanks,**
**The Rax**

**Comment by qiucaixiu** [comment]
Thanks Rax, thank you for the quick response and detail procedure.

**Comment by rakshitshah94** [comment]
Your welcome @qiuqiuqiuqiuqiuqiu . If you think your problem has been resolved, you can close this issue.
