### ISSUE TITLE
Url

### ISSUE THREAD

**Issue by RudraMac** [rakshitshah94/Angular2-SpringBoot-Example#5]
Can u please post  url  of the project

**Comment by rakshitshah94** [comment]
Hello Rudra,

Currently I haven't any java server available to Host this project.
I have attached screenshots, you can also run in your PC/Laptop.

Instead of Angular 2 you can change package JSON dependencies to Angular 4.

Regards,
Rakshit Shah

**Comment by RudraMac** [comment]
Hi
Thanks for your reply. but i am always getting error of angular.json not
found. because it  not there. i saw  angular-cli.json file is there insted
of angular json. so can u please help me solve this. i am using angular 5
and spring boot
Thanks
Rudra

**Comment by rakshitshah94** [comment]
Hi Rudra,

In Angular 2-beta to 2.4.0 we have **angular-cli.json** file. But after angular 4/5 they have changed to ".angular-cli.json", both have major similar concept. I never heard about angular.json, may be it was deprecated when I started to learn angular by myself.

If you are using this example, you have to change package.json (deprecated dependencies and version of angular (for you it is ^5.X.X)) , .angular-cli.json (environment setup) & main.ts etc.

After that you will able to run frontend.
Let me know if you have any issue after this configuration.
Once your code is running, You can also share on your github or your blog/website. or you can create a pull request on this repostory, I will create new branch for you for Angular5-springboot-example (You know its trending for all newbie angular developers), choice is yours.

**Comment by RudraMac** [comment]
thanks
